float64 latitude       #latitude of the vehicle in degrees
float64 longitude      #longitude of the vehicle in degrees
float64 altitude       #altitude of the vehicle in degrees
float64 heading        #heading of the vehicle
float64 x_rotation     #x in quaternion 
float64 y_rotation     #y in quaternion
float64 z_rotation     #z in quaternion
float64 w_rotation     #w in quaternion
float64 x              #cartesian value of the vehicle in the x direction (m)
float64 y              #cartesian value of the vehicle in the y direction (m)
float64 z              #cartesian value of the vehicle in the z direction (m)
int32   id             #vehicle id
